source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FlurryController_Example', :exclusive => true do
  pod "FlurryController", :path => "../"
end

target 'FlurryController_Tests', :exclusive => true do
  pod "FlurryController", :path => "../"

  
end
